version: "3.3"

services:

  api:
    build:
      context: .
    image: mole-covid
    container_name: api
    env_file: docker-compose.env
    command: ["npm", "run", "dev"]
    environment:
      SERVICES: api
      PORT: 3000
    volumes:
      - './services/api.service.js:/app/services/api.service.js'
      - './moleculer.config.js:/app/moleculer.config.js'
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.http.routers.api.rule=Host(`api-7f000001.nip.io`)"
    networks:
      - internal

  greeter:
    build:
      context: .
    image: mole-covid
    container_name: greeter
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    depends_on:
      - nats
    networks:
      - internal

  auth:
    build:
      context: .
    image: mole-covid
    container_name: auth
    env_file: docker-compose.env
    command: ["npm", "run", "dev"]
    volumes:
      - './services/auth.service.js:/app/services/auth.service.js'
      - './moleculer.config.js:/app/moleculer.config.js'
    environment:
      SERVICES: auth
    depends_on:
      - nats
    networks:
      - internal

  products:
    build:
      context: .
    image: mole-covid
    container_name: products
    env_file: docker-compose.env
    environment:
      SERVICES: products
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  users:
    build:
      context: .
    image: mole-covid
    container_name: users
    env_file: docker-compose.env
    command: ["npm", "run", "dev"]
    volumes:
      - './services/users.service.js:/app/services/users.service.js'
      - './moleculer.config.js:/app/moleculer.config.js'
    environment:
      SERVICES: users
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  covid:
    build:
      context: .
    image: mole-covid
    container_name: covid
    env_file: docker-compose.env
    command: ["npm", "run", "dev"]
    volumes:
      - './services/covid.service.js:/app/services/covid.service.js'
      - './moleculer.config.js:/app/moleculer.config.js'
    environment:
      SERVICES: covid
    depends_on:
      - nats
    networks:
      - internal

  geo:
    build:
      context: .
    image: mole-covid
    container_name: geo
    env_file: docker-compose.env
    command: ["npm", "run", "dev"]
    volumes:
      - './services/geo.service.js:/app/services/geo.service.js'
      - './moleculer.config.js:/app/moleculer.config.js'
    environment:
      SERVICES: geo
    depends_on:
      - nats
    networks:
      - internal

  mongo:
    image: mongo:4
    volumes:
      - ./volumes/data:/data/db
    ports:
      - 27017:27017
    networks:
      - internal

  nats:
    image: nats:2
    ports:
      - 4222:4222
    networks:
      - internal

  traefik:
    image: traefik:v2.1
    command:
      - "--ping=true"
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik-7f000001.nip.io`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=traefik:$$apr1$$njk341xt$$w6iZnZbjUSN6hw4O/SvfC1"
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  data:
