---
#########################################################
# Service for Moleculer API Gateway service
#########################################################
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - port: 3000
    targetPort: 3000

---
#########################################################
# Ingress for Moleculer API Gateway
#########################################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moleculer-gateway-ingress
spec:
  rules:
  - host: gateway.192.168.64.7.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port: 
              number: 3000
---
#########################################################
# API Gateway service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: mole-covid
        imagePullPolicy: IfNotPresent
        resources:
          requests:
              memory: "32Mi"
              cpu: "100m"
          limits:
              memory: "64Mi"
              cpu: "300m"
        envFrom:
        - configMapRef:
            name: common-env
        env:
          - name: SERVICES
            value: api
