---
#########################################################
# Greeter service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
spec:
  selector:
    matchLabels:
      app: greeter
  replicas: 1
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - name: greeter
        image: mole-covid
        imagePullPolicy: IfNotPresent
        resources:
          requests:
              memory: "32Mi"
              cpu: "100m"
          limits:
              memory: "64Mi"
              cpu: "300m"
        envFrom:
        - configMapRef:
            name: common-env
        env:
          - name: SERVICES
            value: greeter
