---
#########################################################
# Products service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  replicas: 2
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: mole-covid
        imagePullPolicy: IfNotPresent
        resources:
          requests:
              memory: "32Mi"
              cpu: "100m"
          limits:
              memory: "64Mi"
              cpu: "300m"
        envFrom:
        - configMapRef:
            name: common-env
        env:
          - name: SERVICES
            value: products
